version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Todo
    volumes:
      - /home/ubuntu/db:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    stdin_open: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    depends_on:
      - postgres
    ports:
      - 7000:7000
    volumes:
      - /home/ubuntu/data:/uploads
    restart: always

  frontend:
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - 3100:3100
    restart: always
