version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portal_247db
    volumes:
      - type: bind
        source: C:\CODEQUIVERS\portal-247\data
        target: /var/lib/postgresql/data
    restart: unless-stopped

  backend:
    stdin_open: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    depends_on:
      - postgres
    ports:
      - 7000:7000
    volumes:
      - type: bind
        source: C:\CODEQUIVERS\portal-247\data
        target: /app/uploads
    restart: always

  frontend:
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - 3100:80
    restart: always
